all=set(['John','Mary','Tina','Fiona','Claire','Eva','Ben','Bill','Bert'])
enpass=set(['John','Mary','Fiona','Claire','Ben','Bill'])
mapass=set(['Mary','Fiona','Claire','Eva','Ben'])
print('英文與數學都及格' + str(enpass&mapass))
print('數學不及格' + str(all-mapass))
print('英文及格且數學不及格' + str(enpass&(all-mapass)))